### ISSUE TITLE
Add Spanish Translation

### ISSUE THREAD

**Issue by ned14** [ned14/Easyshop#22]
http://code.google.com/p/easyshop-for-plone/issues/detail?id=45

Reported by manuel@utopiaverde.org, May 16, 2010 
tar.gz attached.

Regards,

Manuel

Attachment: http://easyshop-for-plone.googlecode.com/issues/attachment?aid=-5655260295289645875&name=EasyShop-es-2010.tar.gz&token=41659b614346f30ee89c6a7ba5810985

Comment 1 by nialldouglas14, May 17, 2010 
Thanks for this and the other bugs reported!

I'm currently occupied with a contract whose final deadline is far too close for 
comfort given current progression, so I'll hope to get this and some of the other 
bugs done in June.

Thanks,
Niall

**Comment by spanish** [comment]
In src/easyshop.buildout/products/EasyShopTranslations/i18n/easyshop-es.po

After:
123. Default: "Go to cart"
123: easyshop.carts/easyshop/carts/browser/added_to_cart.pt:103
123: easyshop.customers/easyshop/customers/browser/customers_container.pt:148
msgid "go_to_cart_label"
msgstr "Ir al carrito"

Add:
123. Default: "Checkout"
123: easyshop.carts/easyshop/carts/browser/added_to_cart.pt:109
msgid "go_to_checkout_label"
msgstr "Realizar el pedido"

Note: 123 = # (if I put #, the comment is horrible).

Thanks and sorry (I can't add the file here).

Cordial greetings,

Manuel

**Comment by ned14** [comment]
Yeah I'm sorry you can't add attachments here either. I ought to do something about this.

**Comment by spanish** [comment]
OK. I'm completing the Spanish translation (lacked many phrases in the translation file) and doing several hardcoded i18n.

For example:

1.- I've added i18n:translate="required"9 times in address_form.pt, 3 times in user.pt and 1 times in default_shop_form.pt).

2.- I've added this to easyshop-es.po:
123. Default: "Required"
123: easyshop.checkout/easyshop/checkout/browser/address_form.pt:72
123: easyshop.checkout/easyshop/checkout/browser/address_form.pt:104
123: easyshop.checkout/easyshop/checkout/browser/address_form.pt:136
123: easyshop.checkout/easyshop/checkout/browser/address_form.pt:168
123: easyshop.checkout/easyshop/checkout/browser/address_form.pt:200
123: easyshop.checkout/easyshop/checkout/browser/address_form.pt:232
123: easyshop.checkout/easyshop/checkout/browser/address_form.pt:264
123: easyshop.checkout/easyshop/checkout/browser/address_form.pt:299
123: easyshop.checkout/easyshop/checkout/browser/address_form.pt:331
123: easyshop.checkout/easyshop/checkout/browser/user.pt:74
123: easyshop.checkout/easyshop/checkout/browser/user.pt:106
123: easyshop.checkout/easyshop/checkout/browser/user.pt:138
123: easyshop.core/easyshop/core/browser/default_shop_form.pt:55
msgid "required"
msgstr "Requerido"

(123 = #)

I think that is very important complete i18n metatags and update the .po files.

Greetings,

Manuel

**Comment by ned14** [comment]
FYI I figured out how to attach files to issues so you can attach the latest Spanish translations. See http://github.com/ned14/Easyshop/issues#issue/1.

Niall

**Comment by ned14** [comment]
Committed at http://github.com/ned14/Easyshop/commit/2375205ab06525331d6d7a7cad0caf6211a4efa1
