### ISSUE TITLE
“StartToEndTutorial” have some mistakes

### ISSUE THREAD

**Issue by jianaijun** [ned14/Easyshop#24]
Operate in full accordance with tutorial, the following results:

free@debian:~/Plone/instance2$ bin/buildout 
Develop: '/home/free/Plone/instance2/src/DataGridField-1.7'
Develop: '/home/free/Plone/instance2/src/Easyshop/src/easyshop.core'
Develop: '/home/free/Plone/instance2/src/Easyshop/src/easyshop.carts'
Develop: '/home/free/Plone/instance2/src/Easyshop/src/easyshop.catalog'
Develop: '/home/free/Plone/instance2/src/Easyshop/src/easyshop.checkout'
Develop: '/home/free/Plone/instance2/src/Easyshop/src/easyshop.criteria'
Develop: '/home/free/Plone/instance2/src/Easyshop/src/easyshop.customers'
Develop: '/home/free/Plone/instance2/src/Easyshop/src/easyshop.discounts'
Develop: '/home/free/Plone/instance2/src/Easyshop/src/easyshop.groups'
Develop: '/home/free/Plone/instance2/src/Easyshop/src/easyshop.information'
Develop: '/home/free/Plone/instance2/src/Easyshop/src/easyshop.kss'
Develop: '/home/free/Plone/instance2/src/Easyshop/src/easyshop.login'
Develop: '/home/free/Plone/instance2/src/Easyshop/src/easyshop.management'
Develop: '/home/free/Plone/instance2/src/Easyshop/src/easyshop.order'
Develop: '/home/free/Plone/instance2/src/Easyshop/src/easyshop.payment'
Develop: '/home/free/Plone/instance2/src/Easyshop/src/easyshop.shipping'
error in easyshop.shipping setup command: Distribution contains no modules or packages for namespace package 'easyshop'
While:
  Installing.
  Processing develop directory '/home/free/Plone/instance2/src/Easyshop/src/easyshop.shipping'.

An internal error occured due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/free/Plone/Python-2.4/lib/python2.4/site-packages/zc.buildout-1.4.2-py2.4.egg/zc/buildout/buildout.py", line 1660, in main
    getattr(buildout, command)(args)
  File "/home/free/Plone/Python-2.4/lib/python2.4/site-packages/zc.buildout-1.4.2-py2.4.egg/zc/buildout/buildout.py", line 394, in install
    installed_develop_eggs = self._develop()
  File "/home/free/Plone/Python-2.4/lib/python2.4/site-packages/zc.buildout-1.4.2-py2.4.egg/zc/buildout/buildout.py", line 634, in _develop
    zc.buildout.easy_install.develop(setup, dest)
  File "/home/free/Plone/Python-2.4/lib/python2.4/site-packages/zc.buildout-1.4.2-py2.4.egg/zc/buildout/easy_install.py", line 894, in develop
    assert os.spawnl(os.P_WAIT, executable, _safe_arg(executable),
AssertionError
**************\* PICKED VERSIONS ****************
[versions]

**************\* /PICKED VERSIONS ***************

**Comment by ned14** [comment]
Ach despite one's best efforts one always misses <i>something</i> during a project conversion ...

It ought to be fixed now - simply replace wherever I said src/easyshop.buildout with src/Easyshop. I don't <b>think</b> there are any path name dependencies in the source but I hope you'll report here if there are.

Thanks very much for reporting this bug.

Niall

**Comment by jianaijun** [comment]
free@debian:~/Plone/instance$ cd src
free@debian:~/Plone/instance/src$ ls
README.txt
free@debian:~/Plone/instance/src$ svn checkout https://svn.plone.org/svn/archetypes/Products.DataGridField/trunk DataGridField-1.7
A    DataGridField-1.7/Products
A    DataGridField-1.7/Products/DataGridField
A    DataGridField-1.7/Products/DataGridField/HISTORY.txt
A    DataGridField-1.7/Products/DataGridField/LinesColumn.py
A    DataGridField-1.7/Products/DataGridField/locales
A    DataGridField-1.7/Products/DataGridField/locales/datagridfield.pot
A    DataGridField-1.7/Products/DataGridField/locales/es
A    DataGridField-1.7/Products/DataGridField/locales/es/LC_MESSAGES
A    DataGridField-1.7/Products/DataGridField/locales/es/LC_MESSAGES/datagridfield.po
A    DataGridField-1.7/Products/DataGridField/locales/nl
A    DataGridField-1.7/Products/DataGridField/locales/nl/LC_MESSAGES
A    DataGridField-1.7/Products/DataGridField/locales/nl/LC_MESSAGES/datagridfield.po
A    DataGridField-1.7/Products/DataGridField/locales/manual.pot
A    DataGridField-1.7/Products/DataGridField/locales/rebuild_i18n.sh
A    DataGridField-1.7/Products/DataGridField/profiles
A    DataGridField-1.7/Products/DataGridField/profiles/default
A    DataGridField-1.7/Products/DataGridField/profiles/default/metadata.xml
A    DataGridField-1.7/Products/DataGridField/profiles/default/skins.xml
A    DataGridField-1.7/Products/DataGridField/profiles/example
A    DataGridField-1.7/Products/DataGridField/profiles/example/metadata.xml
A    DataGridField-1.7/Products/DataGridField/profiles/example/types.xml
A    DataGridField-1.7/Products/DataGridField/profiles/example/types
A    DataGridField-1.7/Products/DataGridField/profiles/example/types/MasterSelectDemo.xml
A    DataGridField-1.7/Products/DataGridField/profiles/example/types/FixedRowsDemoType.xml
A    DataGridField-1.7/Products/DataGridField/profiles/example/types/DataGridDemoType.xml
A    DataGridField-1.7/Products/DataGridField/profiles/example/types/DataGridDemoType2.xml
A    DataGridField-1.7/Products/DataGridField/profiles/example/types/InvalidDataGridDemoType.xml
A    DataGridField-1.7/Products/DataGridField/Column.py
A    DataGridField-1.7/Products/DataGridField/SelectColumn.py
A    DataGridField-1.7/Products/DataGridField/configure.zcml
A    DataGridField-1.7/Products/DataGridField/**init**.py
A    DataGridField-1.7/Products/DataGridField/utils.py
A    DataGridField-1.7/Products/DataGridField/skins
A    DataGridField-1.7/Products/DataGridField/skins/DataGridWidget
A    DataGridField-1.7/Products/DataGridField/skins/DataGridWidget/datagrid_fixed_cell.pt
A    DataGridField-1.7/Products/DataGridField/skins/DataGridWidget/datagridwidget_view_row.pt
A    DataGridField-1.7/Products/DataGridField/skins/DataGridWidget/datagrid_lines_cell.pt
A    DataGridField-1.7/Products/DataGridField/skins/DataGridWidget/add_row_icon.gif
A    DataGridField-1.7/Products/DataGridField/skins/DataGridWidget/queryDataGrid.py
A    DataGridField-1.7/Products/DataGridField/skins/DataGridWidget/datagridwidget.js
A    DataGridField-1.7/Products/DataGridField/skins/DataGridWidget/datagrid_select_cell.pt
A    DataGridField-1.7/Products/DataGridField/skins/DataGridWidget/move_row_down_icon.gif
A    DataGridField-1.7/Products/DataGridField/skins/DataGridWidget/datagridwidget_edit_row.pt
A    DataGridField-1.7/Products/DataGridField/skins/DataGridWidget/datagridwidget_manipulators.pt
A    DataGridField-1.7/Products/DataGridField/skins/DataGridWidget/datagrid_text_cell.pt
A    DataGridField-1.7/Products/DataGridField/skins/DataGridWidget/datagridwidget.pt
A    DataGridField-1.7/Products/DataGridField/skins/DataGridWidget/delete_row_icon.gif
A    DataGridField-1.7/Products/DataGridField/skins/DataGridWidget/datagrid_checkbox_cell.pt
A    DataGridField-1.7/Products/DataGridField/skins/DataGridWidget/datagrid_help_cell.pt
A    DataGridField-1.7/Products/DataGridField/skins/DataGridWidget/datagridwidget.css.dtml
A    DataGridField-1.7/Products/DataGridField/skins/DataGridWidget/datagrid_link_cell.pt
A    DataGridField-1.7/Products/DataGridField/skins/DataGridWidget/move_row_up_icon.gif
A    DataGridField-1.7/Products/DataGridField/skins/DataGridWidget/datagrid_radio_cell.pt
A    DataGridField-1.7/Products/DataGridField/CheckboxColumn.py
A    DataGridField-1.7/Products/DataGridField/config.py
A    DataGridField-1.7/Products/DataGridField/HelpColumn.py
A    DataGridField-1.7/Products/DataGridField/validators.py
A    DataGridField-1.7/Products/DataGridField/screenshot.png
A    DataGridField-1.7/Products/DataGridField/LinkColumn.py
A    DataGridField-1.7/Products/DataGridField/tests
A    DataGridField-1.7/Products/DataGridField/tests/testValidators.py
A    DataGridField-1.7/Products/DataGridField/tests/test_data_manipulation.py
A    DataGridField-1.7/Products/DataGridField/tests/DataGridTestCase.py
A    DataGridField-1.7/Products/DataGridField/tests/test_unit.py
A    DataGridField-1.7/Products/DataGridField/tests/**init**.py
A    DataGridField-1.7/Products/DataGridField/tests/test_columns.py
A    DataGridField-1.7/Products/DataGridField/tests/test_setup.py
A    DataGridField-1.7/Products/DataGridField/tests/validators.txt
A    DataGridField-1.7/Products/DataGridField/RadioColumn.py
A    DataGridField-1.7/Products/DataGridField/FixedColumn.py
A    DataGridField-1.7/Products/DataGridField/DataGridWidget.py
A    DataGridField-1.7/Products/DataGridField/DataGridField.py
A    DataGridField-1.7/Products/DataGridField/interfaces.py
A    DataGridField-1.7/Products/DataGridField/README.txt
A    DataGridField-1.7/Products/DataGridField/examples
A    DataGridField-1.7/Products/DataGridField/examples/**init**.py
A    DataGridField-1.7/Products/DataGridField/examples/DataGridDemoType.py
A    DataGridField-1.7/Products/**init**.py
A    DataGridField-1.7/buildout.cfg
A    DataGridField-1.7/setup.py
A    DataGridField-1.7/README.txt
A    DataGridField-1.7/test-plone-4.0.x.cfg
 U   DataGridField-1.7
取出版本 12662。
free@debian:~/Plone/instance/src$ git clone git://github.com/ned14/Easyshop.git
Initialized empty Git repository in /home/free/Plone/instance/src/Easyshop/.git/
remote: Counting objects: 18170, done.
remote: Compressing objects: 100% (6034/6034), done.
remote: Total 18170 (delta 11484), reused 18170 (delta 11484)
Receiving objects: 100% (18170/18170), 6.89 MiB | 213 KiB/s, done.
Resolving deltas: 100% (11484/11484), done.
free@debian:~/Plone/instance/src$ cd ..
free@debian:~/Plone/instance$ vi buildout.cfg 
free@debian:~/Plone/instance$ cd products
free@debian:~/Plone/instance/products$ ln -s ../src/Easyshop/products/EasyShopTranslations EasyShopTranslations
free@debian:~/Plone/instance/products$ cd ..
free@debian:~/Plone/instance$ bin/buildout
Develop: '/home/free/Plone/instance/src/DataGridField-1.7'
Develop: '/home/free/Plone/instance/src/Easyshop/src/easyshop.core'
Develop: '/home/free/Plone/instance/src/Easyshop/src/easyshop.carts'
Develop: '/home/free/Plone/instance/src/Easyshop/src/easyshop.catalog'
Develop: '/home/free/Plone/instance/src/Easyshop/src/easyshop.checkout'
Develop: '/home/free/Plone/instance/src/Easyshop/src/easyshop.criteria'
Develop: '/home/free/Plone/instance/src/Easyshop/src/easyshop.customers'
Develop: '/home/free/Plone/instance/src/Easyshop/src/easyshop.discounts'
Develop: '/home/free/Plone/instance/src/Easyshop/src/easyshop.groups'
Develop: '/home/free/Plone/instance/src/Easyshop/src/easyshop.information'
Develop: '/home/free/Plone/instance/src/Easyshop/src/easyshop.kss'
Develop: '/home/free/Plone/instance/src/Easyshop/src/easyshop.login'
Develop: '/home/free/Plone/instance/src/Easyshop/src/easyshop.management'
Develop: '/home/free/Plone/instance/src/Easyshop/src/easyshop.order'
Develop: '/home/free/Plone/instance/src/Easyshop/src/easyshop.payment'
Develop: '/home/free/Plone/instance/src/Easyshop/src/easyshop.shipping'
error in easyshop.shipping setup command: Distribution contains no modules or packages for namespace package 'easyshop'
While:
  Installing.
  Processing develop directory '/home/free/Plone/instance/src/Easyshop/src/easyshop.shipping'.

An internal error occured due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/free/Plone/Python-2.4/lib/python2.4/site-packages/zc.buildout-1.4.2-py2.4.egg/zc/buildout/buildout.py", line 1660, in main
    getattr(buildout, command)(args)
  File "/home/free/Plone/Python-2.4/lib/python2.4/site-packages/zc.buildout-1.4.2-py2.4.egg/zc/buildout/buildout.py", line 394, in install
    installed_develop_eggs = self._develop()
  File "/home/free/Plone/Python-2.4/lib/python2.4/site-packages/zc.buildout-1.4.2-py2.4.egg/zc/buildout/buildout.py", line 634, in _develop
    zc.buildout.easy_install.develop(setup, dest)
  File "/home/free/Plone/Python-2.4/lib/python2.4/site-packages/zc.buildout-1.4.2-py2.4.egg/zc/buildout/easy_install.py", line 894, in develop
    assert os.spawnl(os.P_WAIT, executable, _safe_arg(executable),
AssertionError
**************\* PICKED VERSIONS ****************
[versions]

**************\* /PICKED VERSIONS ***************

**Comment by jianaijun** [comment]
error in easyshop.shipping setup command: Distribution contains no modules or packages for namespace package 'easyshop'
While:
Installing. Processing develop directory '/home/free/Plone/instance/src/Easyshop/src/easyshop.shipping'.
