### ISSUE TITLE
easyshop for plone 4.0.4

### ISSUE THREAD

**Issue by kyholdings** [ned14/Easyshop#31]
Hi,

My plone now is updated to 4.0.4
When I install the easyshop in my plone site
It show the easyshop only suit for plone 4.0
Could you please help me to get new vision of the easyshop which could be installed in plone4.0.4?

Thanks and Best Wishes
Yours sincerely
Alex Zhang
KY HOLDINGS LIMITED
10/F INT'L BLDG(E) 369 Shuangxi West Road Jinhua Zhejiang China
Tel: +86 579 8239 0958
Fax: +86 579 8239 8501
http://www.kyholding.com
E-mail: alex@kyholdings.com
MSN: zjsources@hotmail.com

**Comment by ned14** [comment]
Surely the Plone_v4.0 branch solves this?

**Comment by kyholdings** [comment]
I have not installed Plone_v4.0,
I have tried the easyshop in Plone_v3.3.5. It works well.
Now I create new app to install Plone_v4.0.4, when I try to install the easyshop, it show the easyshop only suit for Plone_v4.0

**Comment by ned14** [comment]
No, you checkout the Plone_v4.0 branch from this repo, NOT trunk. That's the Plone v4.x compatible version of this code. The problem was that some changes were required for Plone v4.x compatibility that are incompatible with Plone v3.x.

**Comment by kyholdings** [comment]
So could you please let me know how to make the changes ?
I really want to use the easyshop again in my plone site.
Please.

**Comment by ned14** [comment]
There are plenty of good guides on how to use git to change branch e.g. http://www.kernel.org/pub/software/scm/git/docs/v1.7.5.1/git-checkout.html

I'd say this issue is closed as it's RTM.

**Comment by kyholdings** [comment]
[kyholdings@web131 zinstance]$ cd src
[kyholdings@web131 src]$ git checkout Plone_v4.0.4
fatal: Not a git repository (or any of the parent directories): .git

Got Products.DataGridField 1.6.2.
While:
  Installing instance.
Error: There is a version conflict.
We already have: Plone 4.0.4
but easyshop.core 0.1a1dev requires 'Plone<4.0a1'.

This is the bin/buildout run result.
I'm really not know how to change branch with git.
Could you help me to write the commands line?
Thanks for your kindly help

**Comment by ned14** [comment]
The instructions at https://github.com/ned14/Easyshop/wiki/StartToEndTutorial are clear.

The DataFieldGrid version conflict fixes itself with bin/buildout -n

**Comment by ned14** [comment]
You also need to be in the Easyshop directory (the one containing .git) before executing git commands

**Comment by kyholdings** [comment]
Great!
The EasyShop 0.11.alphadev now appeared in add-on products now.
Thanks a lots.

**Comment by kyholdings** [comment]
But there is new problem showed when add-on products finished:

   EasyShop 0.11.alphadev
An out-of-the-box online-shop for Plone.
  This add-on has been upgraded. Old profile version was unknown. New profile version is 0.11 alpha. There is no upgrade procedure defined for this add-on. Please consult the add-on documentation for upgrade information, or contact the add-on author

[kyholdings@web131 zinstance]$ bin/buildout -n
Develop: '/home/kyholdings/webapps/alex/zinstance/src/Easyshop/src/easyshop.core'
install_dir /home/kyholdings/webapps/alex/zinstance/develop-eggs/tmpmHEg8obuild
Develop: '/home/kyholdings/webapps/alex/zinstance/src/Easyshop/src/easyshop.carts'
install_dir /home/kyholdings/webapps/alex/zinstance/develop-eggs/tmpCnKdx5build
Develop: '/home/kyholdings/webapps/alex/zinstance/src/Easyshop/src/easyshop.catalog'
install_dir /home/kyholdings/webapps/alex/zinstance/develop-eggs/tmpDJ_Yhobuild
Develop: '/home/kyholdings/webapps/alex/zinstance/src/Easyshop/src/easyshop.checkout'
install_dir /home/kyholdings/webapps/alex/zinstance/develop-eggs/tmpU_ndEQbuild
Develop: '/home/kyholdings/webapps/alex/zinstance/src/Easyshop/src/easyshop.criteria'
install_dir /home/kyholdings/webapps/alex/zinstance/develop-eggs/tmp9Sa4K6build
Develop: '/home/kyholdings/webapps/alex/zinstance/src/Easyshop/src/easyshop.customers'
install_dir /home/kyholdings/webapps/alex/zinstance/develop-eggs/tmpvJpEH7build
Develop: '/home/kyholdings/webapps/alex/zinstance/src/Easyshop/src/easyshop.discounts'
install_dir /home/kyholdings/webapps/alex/zinstance/develop-eggs/tmpXyceoebuild
Develop: '/home/kyholdings/webapps/alex/zinstance/src/Easyshop/src/easyshop.groups'
install_dir /home/kyholdings/webapps/alex/zinstance/develop-eggs/tmpNMUziIbuild
Develop: '/home/kyholdings/webapps/alex/zinstance/src/Easyshop/src/easyshop.information'
install_dir /home/kyholdings/webapps/alex/zinstance/develop-eggs/tmpk6QcEBbuild
Develop: '/home/kyholdings/webapps/alex/zinstance/src/Easyshop/src/easyshop.kss'
install_dir /home/kyholdings/webapps/alex/zinstance/develop-eggs/tmplz2fsEbuild
Develop: '/home/kyholdings/webapps/alex/zinstance/src/Easyshop/src/easyshop.login'
install_dir /home/kyholdings/webapps/alex/zinstance/develop-eggs/tmpoiGavLbuild
Develop: '/home/kyholdings/webapps/alex/zinstance/src/Easyshop/src/easyshop.management'
install_dir /home/kyholdings/webapps/alex/zinstance/develop-eggs/tmp_btnkObuild
Develop: '/home/kyholdings/webapps/alex/zinstance/src/Easyshop/src/easyshop.order'
install_dir /home/kyholdings/webapps/alex/zinstance/develop-eggs/tmpqgrDzMbuild
Develop: '/home/kyholdings/webapps/alex/zinstance/src/Easyshop/src/easyshop.payment'
install_dir /home/kyholdings/webapps/alex/zinstance/develop-eggs/tmpV6G3CJbuild
Develop: '/home/kyholdings/webapps/alex/zinstance/src/Easyshop/src/easyshop.shipping'
install_dir /home/kyholdings/webapps/alex/zinstance/develop-eggs/tmpgsghorbuild
Develop: '/home/kyholdings/webapps/alex/zinstance/src/Easyshop/src/easyshop.shop'
install_dir /home/kyholdings/webapps/alex/zinstance/develop-eggs/tmpy1v8fgbuild
Develop: '/home/kyholdings/webapps/alex/zinstance/src/Easyshop/src/easyshop.stocks'
install_dir /home/kyholdings/webapps/alex/zinstance/develop-eggs/tmpj9gD63build
Develop: '/home/kyholdings/webapps/alex/zinstance/src/Easyshop/src/easyshop.taxes'
install_dir /home/kyholdings/webapps/alex/zinstance/develop-eggs/tmpK97Kblbuild
Unused options for buildout: 'zope-conf-additional'.
Updating instance.
Download error: [Errno -2] Name or service not known -- Some packages may not be found!
.

**Comment by ned14** [comment]
I wouldn't worry about upgrade procedures. I simply didn't bother defining one, it hardly matters.

The name or service not known will be due to some download not resolving. I don't know what you have in your buildout.cfg, so I cannot say.

In case you get tempted to post your buildout.cfg here for answers, buildout problems really ought to be directed to the Plone guys at their support mailing lists. I'd suggest fiddling with the buildout command line options to find out what's not resolving. It may also be firewall, DNS, or simply a dead server.

I might add that in the long run Easyshop will get ditched - this is why there has been no new development for so long. This is because Plone 5's Deco UI makes most of Easyshop obsolete.
