### ISSUE TITLE
Checkout with asynchronous payment deletes cart before obtaining payment status

### ISSUE THREAD

**Issue by ned14** [ned14/Easyshop#6]
http://code.google.com/p/easyshop-for-plone/issues/detail?id=25

Reported by pedrotschki, Oct 06, 2009 
ok, this is not a bug, but a question to all ES developers:

if you have an asynchronous payment method (PayPal, MPAY24) the cart will
be deleted and the orderReceived mail will be sent before successfull payment.

i think it would be nicer if the asynchron payment plugin takes care, when
the cart will be deleted and when the mails will be fired. so you doesn't
loose your cart items if there is an error during payment process for
example and the customer wont get confused by order mails while not having
paid yet.

what does the ES community think?

regards
peter

Comment 1 by nialldouglas14, Mar 15, 2010 
I too have this problem, plus the related problem that the order status is not
changed to paid when the Paypal payment is made.

I shall commit a fix for this shortly.

Niall

**Comment by petschki** [comment]
i think, there was a branch on googlecode, where i fixed this issue ... have to look at the migrated data.

and for the record: pedrotschki (google) = petschki (github) :-)
